"""Structural backend contract shared by mock, dry-run, and future live drivers."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class CHI760Backend(Protocol):
    def connect(self) -> bool: ...

    def disconnect(self) -> None: ...

    def run_cv(self, **params: Any) -> dict[str, Any]: ...

    def run_it(self, **params: Any) -> dict[str, Any]: ...

    def run_lsv(self, **params: Any) -> dict[str, Any]: ...

    def run_eis(self, **params: Any) -> dict[str, Any]: ...

    def run_ocp(self, **params: Any) -> dict[str, Any]: ...

    def run_ca(self, **params: Any) -> dict[str, Any]: ...

    def run_swv(self, **params: Any) -> dict[str, Any]: ...

    def run_impe(self, **params: Any) -> dict[str, Any]: ...

    def run_step(self, **params: Any) -> dict[str, Any]: ...

    def run_istep(self, **params: Any) -> dict[str, Any]: ...
